Delete from MORPION.GAME_CONTENT;
Delete from MORPION.GAME;
Delete from MORPION.PLAYER;

Insert into MORPION.PLAYER (PLAYER_ID,DISPLAY_NAME,FIRST_NAME,LAST_NAME,EMAIL,PHONE,CREATE_BY,CREATE_ON,UPDATE_BY,UPDATE_ON,USERNAME,PASSWORD) values (4,'NAT','Reneaud','Desormeau','renodesor@yahoo.fr',null,'tata',to_date('23-MAR-2024 15.04.33','DD-MON-RRRR HH24.MI.SS'),'null',null,'reno','reno');
Insert into MORPION.PLAYER (PLAYER_ID,DISPLAY_NAME,FIRST_NAME,LAST_NAME,EMAIL,PHONE,CREATE_BY,CREATE_ON,UPDATE_BY,UPDATE_ON,USERNAME,PASSWORD) values (1,'NAU','Reneaud','Desormeau','renodesor@yahoo.fr',null,'toto',to_date('2024-03-23','RRRR-MM-DD'),'null',null,'reno','reno');
Insert into MORPION.PLAYER (PLAYER_ID,DISPLAY_NAME,FIRST_NAME,LAST_NAME,EMAIL,PHONE,CREATE_BY,CREATE_ON,UPDATE_BY,UPDATE_ON,USERNAME,PASSWORD) values (2,'WIS','Wisline','Pierre-Louis','wisline_pl@yahoo.fr',null,'toto',to_date('2024-MAR-23','RRRR-MON-DD'),'null',null,'wisl','wisl');

Insert into MORPION.GAME (GAME_ID,NUMBER_OF_LINES,NUMBER_OF_COLUMNS,QTY_SQUARES_FOR_WINNER,FIRST_PLAYER_ID,SECOND_PLAYER_ID,GAME_STATUS,CREATE_BY,CREATE_ON,UPDATE_BY,UPDATE_ON) values (2,5,5,3,1,2,'RUNNING', 'toto',to_date('23-MAR-2024 15.16.26','DD-MON-RRRR HH24.MI.SS'),'toto',to_date('23-MAR-2024 15.16.26','DD-MON-RRRR HH24.MI.SS'));
Insert into MORPION.GAME (GAME_ID,NUMBER_OF_LINES,NUMBER_OF_COLUMNS,QTY_SQUARES_FOR_WINNER,FIRST_PLAYER_ID,SECOND_PLAYER_ID,GAME_STATUS,CREATE_BY,CREATE_ON,UPDATE_BY,UPDATE_ON) values (1,20,10,5,2,1,'RUNNING', 'toto',to_date('23-MAR-2024 15.16.26','DD-MON-RRRR HH24.MI.SS'),'toto',to_date('23-MAR-2024 15.16.26','DD-MON-RRRR HH24.MI.SS'));

Insert into MORPION.GAME_CONTENT (GAME_ID,SQUARES_DATA,MOVES_HISTORY,CREATE_BY,CREATE_ON,UPDATE_BY,UPDATE_ON) values (1,'{''s00'':2, ''s01'':0, ''s02'':1, ''s03'':0}','{''s00'':2, ''s01'':0, ''s02'':1, ''s03'':0}','TOTO',to_date('25-MAR-2024 21.47.29','DD-MON-RRRR HH24.MI.SS'),null,null);
Insert into MORPION.GAME_CONTENT (GAME_ID,SQUARES_DATA,MOVES_HISTORY,CREATE_BY,CREATE_ON,UPDATE_BY,UPDATE_ON) values (2,'{''s00'':2, ''s01'':0, ''s02'':1, ''s03'':0, ''s04'':2, ''s05'':1, ''s06'':0, ''s07'':2}','{''s00'':2, ''s01'':0, ''s02'':1, ''s03'':0, ''s04'':2, ''s05'':1, ''s06'':0, ''s07'':2}','TOTO',to_date('25-MAR-2024 21.47.29','DD-MON-RRRR HH24.MI.SS'),null,null);
