-----------------------------------------------
SET MODE ORACLE;

CREATE SCHEMA IF NOT EXISTS MORPION;

CREATE TABLE IF NOT EXISTS MORPION.PLAYER(
  PLAYER_ID NUMBER NOT NULL
, DISPLAY_NAME VARCHAR2(3) NOT NULL
, FIRST_NAME VARCHAR2(50)
, LAST_NAME VARCHAR2(50)
, EMAIL VARCHAR2(100) NOT NULL
, PHONE NUMBER(12)
, USERNAME VARCHAR2(30) NOT NULL
, PASSWORD VARCHAR2(100) NOT NULL
, CREATE_BY VARCHAR2(30) NOT NULL
, CREATE_ON DATE NOT NULL
, UPDATE_BY VARCHAR2(30)
, UPDATE_ON DATE
, CONSTRAINT PLAYER_PK PRIMARY KEY (PLAYER_ID)
);
ALTER TABLE MORPION.PLAYER ADD CONSTRAINT IF NOT EXISTS PLAYER_DISPLAYNAME_UK UNIQUE (DISPLAY_NAME);

CREATE TABLE IF NOT EXISTS MORPION.GAME(
  GAME_ID NUMBER NOT NULL
, NUMBER_OF_LINES NUMBER(2) NOT NULL
, NUMBER_OF_COLUMNS NUMBER(2) NOT NULL
, QTY_SQUARES_FOR_WINNER NUMBER(2) NOT NULL
, FIRST_PLAYER_ID NUMBER NOT NULL
, SECOND_PLAYER_ID NUMBER NOT NULL
, GAME_STATUS VARCHAR2(12) DEFAULT 'NOT STARTED' NOT NULL
, CREATE_BY VARCHAR2(30) NOT NULL
, CREATE_ON DATE NOT NULL
, UPDATE_BY VARCHAR2(30)
, UPDATE_ON DATE
, CONSTRAINT GAME_PK PRIMARY KEY (GAME_ID)
);

ALTER TABLE MORPION.GAME
ADD CONSTRAINT IF NOT EXISTS GAME_FIRSTPLAYER_FK FOREIGN KEY
(FIRST_PLAYER_ID) REFERENCES MORPION.PLAYER (PLAYER_ID);

ALTER TABLE MORPION.GAME
ADD CONSTRAINT IF NOT EXISTS GAME_SECONDPLAYER_FK FOREIGN KEY
(SECOND_PLAYER_ID) REFERENCES MORPION.PLAYER(PLAYER_ID);

ALTER TABLE MORPION.GAME ADD CONSTRAINT IF NOT EXISTS GAME_STATUS_CHK CHECK
(GAME_STATUS IN ('NOT STARTED', 'RUNNING', 'CANCELLED', 'COMPLETED'));

CREATE TABLE IF NOT EXISTS MORPION.GAME_CONTENT(
	GAME_ID NUMBER NOT NULL,
	SQUARES_DATA CLOB,
	MOVES_HISTORY CLOB,
	CREATE_BY VARCHAR2(30) NOT NULL,
    CREATE_ON DATE NOT NULL,
    UPDATE_BY VARCHAR2(30),
    UPDATE_ON DATE,
	 CONSTRAINT GAME_CONTENT_PK PRIMARY KEY (GAME_ID),
	 CONSTRAINT GAME_GAMECONTENT_FK FOREIGN KEY (GAME_ID) REFERENCES MORPION.GAME (GAME_ID)
);

CREATE SEQUENCE IF NOT EXISTS MORPION.GAME_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 ORDER;

CREATE SEQUENCE IF NOT EXISTS MORPION.PLAYER_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1;
